import type { AnalysisResult, HumanReviewItem } from "./types";

export const MOCK_ANALYSIS: AnalysisResult = {
  caseId: "CASE-2024-0847",
  snapshot: {
    id: "CASE-2024-0847",
    applicantName: "Sarah Chen",
    applicationDate: "2024-06-15T09:30:00Z",
    documents: [
      {
        id: "doc-1",
        name: "Q2_Invoices_Summary.pdf",
        type: "invoice",
        size: 2457600,
        uploadedAt: "2024-06-15T09:31:00Z",
        status: "ready",
      },
      {
        id: "doc-2",
        name: "Monthly_Spend_Export.csv",
        type: "spend-export",
        size: 156400,
        uploadedAt: "2024-06-15T09:32:00Z",
        status: "ready",
      },
      {
        id: "doc-3",
        name: "Employment_Contract.pdf",
        type: "contract",
        size: 890000,
        uploadedAt: "2024-06-15T09:33:00Z",
        status: "ready",
      },
      {
        id: "doc-4",
        name: "Bank_Statement_May.pdf",
        type: "bank-statement",
        size: 1200000,
        uploadedAt: "2024-06-15T09:34:00Z",
        status: "ready",
      },
    ],
    monthlyIncome: 8500,
    monthlyExpenses: 5200,
    debtToIncome: 0.28,
    savingsRate: 0.18,
    validationStatus: "valid",
    validationIssues: [],
  },
  agentReports: [
    {
      agentId: "evidence",
      agentName: "Evidence Agent",
      status: "complete",
      startedAt: "2024-06-15T09:35:00Z",
      completedAt: "2024-06-15T09:36:12Z",
      score: 82,
      confidence: 0.91,
      summary:
        "Document authenticity verified. 4 of 4 documents passed integrity checks. Minor discrepancy in invoice dates flagged for review.",
      findings: [
        {
          id: "ef-1",
          category: "Document Integrity",
          severity: "low",
          title: "All documents cryptographically verified",
          description:
            "PDF signatures and metadata consistent with legitimate sources.",
          evidence: ["Q2_Invoices_Summary.pdf: SHA-256 match", "Employment_Contract.pdf: Digital signature valid"],
          confidence: 0.95,
        },
        {
          id: "ef-2",
          category: "Data Consistency",
          severity: "medium",
          title: "Invoice date range mismatch",
          description:
            "Q2 invoices show dates spanning April–June but filename suggests Q2 only. Amounts reconcile.",
          evidence: ["Invoice #1042 dated March 28", "Invoice #1089 dated June 30"],
          confidence: 0.78,
        },
        {
          id: "ef-3",
          category: "Duplicate Detection",
          severity: "low",
          title: "No duplicate submissions detected",
          description: "Cross-referenced against 12,400 historical submissions.",
          evidence: ["Hash comparison: 0 matches"],
          confidence: 0.99,
        },
      ],
      metrics: {
        documentsVerified: 4,
        integrityScore: 98,
        duplicatesFound: 0,
        extractionAccuracy: 96,
      },
      reasoning: [
        "Parsed 4 uploaded documents via OCR pipeline",
        "Validated PDF metadata against known vendor signatures",
        "Cross-referenced invoice amounts with bank statement deposits",
        "Flagged minor date inconsistency — does not affect total amounts",
      ],
    },
    {
      agentId: "affordability",
      agentName: "Affordability Agent",
      status: "complete",
      startedAt: "2024-06-15T09:35:02Z",
      completedAt: "2024-06-15T09:36:45Z",
      score: 76,
      confidence: 0.87,
      summary:
        "Applicant demonstrates stable income with healthy savings rate. Recurring obligations are manageable but subscription creep detected.",
      findings: [
        {
          id: "af-1",
          category: "Income Stability",
          severity: "low",
          title: "Consistent monthly income",
          description:
            "Employment contract confirms $8,500/month base salary. Bank deposits align within 2% variance.",
          evidence: ["3-month deposit average: $8,420", "Contract start: Jan 2022"],
          confidence: 0.92,
        },
        {
          id: "af-2",
          category: "Spend Behavior",
          severity: "medium",
          title: "Subscription spend increasing",
          description:
            "Recurring subscriptions grew 23% over 6 months. Currently $340/month across 12 services.",
          evidence: ["Jan subscriptions: $276/mo", "Jun subscriptions: $340/mo"],
          confidence: 0.85,
        },
        {
          id: "af-3",
          category: "Savings",
          severity: "low",
          title: "Positive savings trajectory",
          description: "18% savings rate exceeds benchmark of 15% for income bracket.",
          evidence: ["Monthly savings: ~$1,530", "Emergency fund: 3.2 months expenses"],
          confidence: 0.88,
        },
      ],
      metrics: {
        monthlyIncome: 8500,
        monthlyExpenses: 5200,
        disposableIncome: 3300,
        savingsRate: 18,
        subscriptionSpend: 340,
      },
      reasoning: [
        "Analyzed 90-day spend patterns from bank statement and CSV export",
        "Identified 12 recurring subscriptions totaling $340/month",
        "Calculated debt-to-income at 28% — within acceptable range",
        "Compared savings rate against peer cohort benchmarks",
      ],
    },
    {
      agentId: "credit-risk",
      agentName: "Credit Risk Agent",
      status: "complete",
      startedAt: "2024-06-15T09:35:04Z",
      completedAt: "2024-06-15T09:37:01Z",
      score: 71,
      confidence: 0.84,
      summary:
        "Moderate credit risk profile. Payment history is strong but utilization spikes and one late payment in past 12 months noted.",
      findings: [
        {
          id: "cr-1",
          category: "Payment History",
          severity: "medium",
          title: "One late payment detected",
          description:
            "Credit card payment 18 days late in February. All other payments on time.",
          evidence: ["Feb 2024: 18-day delinquency on Chase Sapphire", "11/12 months on-time"],
          confidence: 0.94,
        },
        {
          id: "cr-2",
          category: "Utilization",
          severity: "medium",
          title: "Credit utilization spike",
          description:
            "Utilization peaked at 68% in April before dropping to 42% in May.",
          evidence: ["Apr utilization: 68%", "May utilization: 42%", "Current: 38%"],
          confidence: 0.89,
        },
        {
          id: "cr-3",
          category: "Debt Load",
          severity: "low",
          title: "Manageable total debt",
          description:
            "Total outstanding debt $24,200 against annual income $102,000. DTI at 28%.",
          evidence: ["Student loan: $18,400", "Credit cards: $5,800"],
          confidence: 0.91,
        },
      ],
      metrics: {
        creditScore: 712,
        utilization: 38,
        totalDebt: 24200,
        onTimePayments: 92,
        accountsInGoodStanding: 4,
      },
      reasoning: [
        "Pulled credit indicators from uploaded bank statement patterns",
        "Detected utilization spike correlating with large purchase in April",
        "Late payment isolated incident — subsequent 4 months perfect",
        "Debt-to-income within policy threshold of 35%",
      ],
    },
    {
      agentId: "manager",
      agentName: "Manager Agent",
      status: "complete",
      startedAt: "2024-06-15T09:37:05Z",
      completedAt: "2024-06-15T09:37:48Z",
      score: 77,
      confidence: 0.86,
      summary:
        "Aggregated analysis indicates moderate-low risk. One conflict between Evidence and Affordability agents resolved. Recommends approval with subscription monitoring condition.",
      findings: [
        {
          id: "mf-1",
          category: "Aggregation",
          severity: "low",
          title: "Agent consensus reached",
          description:
            "3 specialist agents completed analysis. Weighted credibility score: 77/100.",
          evidence: ["Evidence: 82", "Affordability: 76", "Credit Risk: 71"],
          confidence: 0.86,
        },
        {
          id: "mf-2",
          category: "Policy",
          severity: "medium",
          title: "Conditional approval recommended",
          description:
            "Subscription spend trend warrants 90-day monitoring period per policy POL-2847.",
          evidence: ["POL-2847: Subscription creep >20% triggers monitoring"],
          confidence: 0.9,
        },
      ],
      metrics: {
        agentsConsulted: 3,
        conflictsDetected: 1,
        conflictsResolved: 1,
        policyChecksPassed: 8,
        policyChecksFailed: 1,
      },
      reasoning: [
        "Received structured reports from Evidence, Affordability, and Credit Risk agents",
        "Detected conflict on income verification methodology — resolved via bank deposit cross-check",
        "Applied policy engine: 8/9 checks passed",
        "Weighted scores: Evidence 30%, Affordability 35%, Credit Risk 35%",
        "Final recommendation: Approve with conditions",
      ],
    },
  ],
  agentMessages: [
    {
      id: "msg-1",
      from: "evidence",
      to: "broadcast",
      timestamp: "2024-06-15T09:36:15Z",
      type: "analysis",
      content:
        "Evidence analysis complete. 4/4 documents verified. Minor invoice date discrepancy flagged — amounts reconcile.",
    },
    {
      id: "msg-2",
      from: "affordability",
      to: "broadcast",
      timestamp: "2024-06-15T09:36:48Z",
      type: "analysis",
      content:
        "Affordability assessment complete. Income stable at $8,500/mo. Subscription creep +23% over 6 months — flagging for manager review.",
    },
    {
      id: "msg-3",
      from: "credit-risk",
      to: "broadcast",
      timestamp: "2024-06-15T09:37:04Z",
      type: "analysis",
      content:
        "Credit risk profile: moderate. One late payment (Feb), utilization normalized to 38%. DTI 28% — within policy.",
    },
    {
      id: "msg-4",
      from: "affordability",
      to: "evidence",
      timestamp: "2024-06-15T09:37:06Z",
      type: "question",
      content:
        "Evidence Agent: Can you confirm employment contract salary matches bank deposit patterns? My analysis shows $8,420 avg vs $8,500 stated.",
    },
    {
      id: "msg-5",
      from: "evidence",
      to: "affordability",
      timestamp: "2024-06-15T09:37:10Z",
      type: "response",
      content:
        "Confirmed. Contract shows $8,500 gross; bank deposits reflect net after tax/401k (~$8,420). No discrepancy — pre vs post-tax difference.",
    },
    {
      id: "msg-6",
      from: "manager",
      to: "broadcast",
      timestamp: "2024-06-15T09:37:12Z",
      type: "conflict",
      content:
        "Conflict detected: Affordability flagged income variance. Evidence Agent resolved — pre/post-tax difference. Marking resolved.",
    },
    {
      id: "msg-7",
      from: "manager",
      to: "broadcast",
      timestamp: "2024-06-15T09:37:50Z",
      type: "resolution",
      content:
        "Final aggregation complete. Credibility score: 77/100. Recommendation: Approve with 90-day subscription monitoring (POL-2847).",
    },
  ],
  conflicts: [
    {
      id: "conf-1",
      agents: ["evidence", "affordability"],
      topic: "Income amount verification",
      description:
        "Affordability Agent detected $80/month variance between stated income and bank deposits. Evidence Agent clarified as pre vs post-tax.",
      severity: "medium",
      resolution:
        "Resolved: Contract gross salary ($8,500) vs net deposits ($8,420) after tax withholding and 401k contributions.",
      resolved: true,
    },
  ],
  policyChecks: [
    { id: "pol-1", rule: "DTI below 35%", status: "pass", details: "Current DTI: 28%" },
    { id: "pol-2", rule: "Minimum credibility score 60", status: "pass", details: "Score: 77" },
    { id: "pol-3", rule: "Document verification required", status: "pass", details: "4/4 documents verified" },
    { id: "pol-4", rule: "No critical risk findings", status: "pass", details: "0 critical findings" },
    { id: "pol-5", rule: "Savings rate above 10%", status: "pass", details: "Savings rate: 18%" },
    { id: "pol-6", rule: "Subscription creep below 20%", status: "fail", details: "Subscription growth: 23% — triggers POL-2847 monitoring" },
    { id: "pol-7", rule: "Payment history above 90%", status: "pass", details: "On-time payments: 92%" },
    { id: "pol-8", rule: "Credit utilization below 50%", status: "pass", details: "Current utilization: 38%" },
    { id: "pol-9", rule: "All agent reports complete", status: "pass", details: "4/4 agents reported" },
  ],
  credibility: {
    evidenceScore: 82,
    affordabilityScore: 76,
    creditRiskScore: 71,
    overallScore: 77,
    riskLevel: "low",
    confidence: 0.86,
  },
  spendCategories: [
    { name: "Housing", amount: 1800, percentage: 34.6, trend: "stable" },
    { name: "Food & Dining", amount: 680, percentage: 13.1, trend: "up", riskFlag: false },
    { name: "Transportation", amount: 420, percentage: 8.1, trend: "stable" },
    { name: "Subscriptions", amount: 340, percentage: 6.5, trend: "up", riskFlag: true },
    { name: "Utilities", amount: 280, percentage: 5.4, trend: "stable" },
    { name: "Healthcare", amount: 250, percentage: 4.8, trend: "stable" },
    { name: "Entertainment", amount: 320, percentage: 6.2, trend: "up" },
    { name: "Shopping", amount: 510, percentage: 9.8, trend: "down" },
    { name: "Debt Payments", amount: 600, percentage: 11.5, trend: "stable" },
  ],
  recurringBills: [
    { vendor: "Rent — Oakwood Apts", amount: 1800, frequency: "monthly", nextDue: "2024-07-01", verified: true, duplicateRisk: false },
    { vendor: "Netflix", amount: 15.99, frequency: "monthly", nextDue: "2024-06-22", verified: true, duplicateRisk: false },
    { vendor: "Spotify", amount: 10.99, frequency: "monthly", nextDue: "2024-06-18", verified: true, duplicateRisk: false },
    { vendor: "Adobe Creative Cloud", amount: 54.99, frequency: "monthly", nextDue: "2024-06-25", verified: true, duplicateRisk: false },
    { vendor: "Planet Fitness", amount: 24.99, frequency: "monthly", nextDue: "2024-06-20", verified: true, duplicateRisk: false },
    { vendor: "AWS Cloud Services", amount: 47.00, frequency: "monthly", nextDue: "2024-06-28", verified: false, duplicateRisk: true },
    { vendor: "Student Loan — Navient", amount: 312, frequency: "monthly", nextDue: "2024-07-05", verified: true, duplicateRisk: false },
  ],
  savingsOpportunities: [
    {
      id: "sav-1",
      title: "Consolidate streaming subscriptions",
      potentialSavings: 45,
      category: "Subscriptions",
      confidence: 0.82,
      action: "Bundle Netflix + Spotify via carrier plan; cancel duplicate HBO Max",
    },
    {
      id: "sav-2",
      title: "Resolve duplicate cloud hosting",
      potentialSavings: 47,
      category: "Subscriptions",
      confidence: 0.91,
      action: "AWS charge may duplicate existing Vercel hosting — verify and cancel one",
    },
    {
      id: "sav-3",
      title: "Refinance student loan",
      potentialSavings: 68,
      category: "Debt",
      confidence: 0.65,
      action: "Current rate 6.8% — market rates at 5.2% for qualified borrowers",
    },
    {
      id: "sav-4",
      title: "Reduce dining out frequency",
      potentialSavings: 120,
      category: "Food & Dining",
      confidence: 0.74,
      action: "Dining spend up 18% — meal prep could save ~$120/month",
    },
  ],
  decision: {
    outcome: "approved-with-conditions",
    rationale: [
      "Credibility score 77/100 exceeds minimum threshold of 60",
      "Stable income with healthy 18% savings rate",
      "One resolved conflict — no outstanding agent disagreements",
      "Subscription creep triggers POL-2847 monitoring condition",
    ],
    conditions: [
      "90-day subscription spend monitoring",
      "Re-submit spend export at 90-day mark",
      "Maintain DTI below 35%",
    ],
    reviewedBy: "Manager Agent",
    decidedAt: "2024-06-15T09:37:50Z",
  },
  pipelineStage: "complete",
};

export const MOCK_REVIEW_QUEUE: HumanReviewItem[] = [
  {
    id: "rev-1",
    caseId: "CASE-2024-0847",
    applicantName: "Sarah Chen",
    submittedAt: "2024-06-15T09:37:50Z",
    priority: "medium",
    reason: "Subscription creep policy violation — conditional approval review",
    credibilityScore: 77,
    riskLevel: "low",
    status: "pending",
  },
  {
    id: "rev-2",
    caseId: "CASE-2024-0831",
    applicantName: "Marcus Williams",
    submittedAt: "2024-06-14T14:22:00Z",
    priority: "high",
    reason: "Agent conflict unresolved — Evidence vs Credit Risk on income source",
    credibilityScore: 54,
    riskLevel: "high",
    status: "in-review",
    assignedTo: "J. Patel",
  },
  {
    id: "rev-3",
    caseId: "CASE-2024-0819",
    applicantName: "Elena Rodriguez",
    submittedAt: "2024-06-13T11:05:00Z",
    priority: "urgent",
    reason: "Critical risk finding — potential document fraud detected",
    credibilityScore: 31,
    riskLevel: "critical",
    status: "pending",
  },
  {
    id: "rev-4",
    caseId: "CASE-2024-0802",
    applicantName: "David Kim",
    submittedAt: "2024-06-12T16:40:00Z",
    priority: "low",
    reason: "Borderline affordability score — manager override requested",
    credibilityScore: 62,
    riskLevel: "medium",
    status: "resolved",
    assignedTo: "A. Thompson",
  },
];
